# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Welcome to the Superheroes API project! ğŸ¦¸â€â™‚ï¸ Be sure to follow the issue template!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! ğŸ¦¸â€â™€ï¸ Please check out our contributing guidelines. Let's make the Superheroes API even better!

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ We here at the Superheroes API are proud of you! You've just leveled up like a true superhero! ğŸ¦¸â€â™‚ï¸ğŸ’ª

# It is recommend to include as many gifs and emojis as possible